<li>
                    <h3>
                        <a href="{dede:field name='typeurl'/}" target="_blank">
                            {dede:field name='typename'/}
                        </a>
                    </h3>
                    <div class="content clearfix">
                        {dede:channel type='son' noself='yes'}
                        <a href="[field:typelink/]" target="_blank">
                            [field:typename/]
                        </a>
                        {/dede:channel}
                    </div>
                </li>