<?php
$z[0]=Array("field","",65,93);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",141,170);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                        <a href=\"[field:typelink/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",305,531);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>