<div class="clearfix li">
                        <div class="pic fl">
                            <img src="[field:litpic/]" style="border: none" alt="[field:title /]">
                        </div>
                        <div class="ul-box1-article fl">
                            <h3>[field:title /]</h3>
                            <p>[field:description function="cn_substr(@me,120)"/]... <span><a href="[field:arcurl /]" target="_blank">【查看更多】</a></span></p>
                        </div>
                    </div>