<?php
$z[0]=Array("field","",103,132);
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n                         <a href=\"[field:typelink/]\" target=\"_blank\">\r\n                              [field:typename/]\r\n                          </a>\r\n                          ",193,426);
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n                            <a href=\"[field:arcurl /]\" target=\"_blank\">\r\n                                 [field:title /]\r\n                             </a>\r\n                        ",482,745);
$z[2][4]['row']="4";
$z[2][4]['flag']="s";
$z[2][4]['orderby']="pubdate";
$z[2][4]['titlelen']="46";
$z[3]=Array("field","",876,904);
$z[3][4]['name']="typeurl";
$z[4]=Array("arclist","\r\n                    <div class=\"clearfix li\">\r\n                        <div class=\"pic fl\">\r\n                            <img src=\"[field:litpic/]\" style=\"border: none\" alt=\"[field:title /]\">\r\n                        </div>\r\n                        <div class=\"ul-box1-article fl\">\r\n                            <h3>[field:title /]</h3>\r\n                            <p>[field:description function=\"cn_substr(@me,120)\"/]... <span><a href=\"[field:arcurl /]\"\r\n                                                                                              target=\"_blank\">【查看更多】</a></span>\r\n                            </p>\r\n                        </div>\r\n                    </div>\r\n                    ",1103,1893);
$z[4][4]['pagesize']="1";
$z[4][4]['flag']="p";
$z[4][4]['titlelen']="46";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n                            <li>\r\n                                <a href=\"[field:arcurl /] \" target=\"_blank\">\r\n                                    [field:title /]\r\n                                </a>\r\n                            </li>\r\n                            ",2025,2362);
$z[5][4]['row']="6";
$z[5][4]['titlelen']="46";
$z[5][4]['orderby']="pubdate";

?>