
<field:zhuanjianame itemname="专家" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhuanjianame>

<field:zuozhentime itemname="坐诊时间" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zuozhentime>

<field:zhicheng itemname="职称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng>
