<li class="clearfix">
                    <div class="fl">
                        <img src="[field:litpic/]" style="border: none" alt="[field:title /]">
                    </div>
                    <div class="fr">
                        <h3>[field:title/]</h3>
                        <p>坐诊时间 :</p>
                        <p><ins>每周四</ins>下午13:30-17:00</p>
                        <p>
                            [field:description function="cn_substr(@me,120)"/]......
                            <span>
                            <a href="[field:arcurl /]" target="_blank">[详情]</a>
                        </span>
                        </p>
                    </div>
                </li>