<?php
$z[0]=Array("field","",103,132);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n                            <a href=\"[field:arcurl /]\" target=\"_blank\">\r\n                                 [field:title /]\r\n                             </a>\r\n                        ",192,455);
$z[1][4]['row']="4";
$z[1][4]['flag']="s";
$z[1][4]['orderby']="pubdate";
$z[1][4]['titlelen']="46";
$z[2]=Array("field","",527,555);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n                    <div class=\"clearfix li\">\r\n                        <div class=\"pic fl\">\r\n                            <img src=\"[field:litpic/]\" style=\"border: none\" alt=\"[field:title /]\">\r\n                        </div>\r\n                        <div class=\"ul-box1-article fl\">\r\n                            <h3>[field:title /]</h3>\r\n                            <p>[field:description function=\"cn_substr(@me,120)\"/]... <span><a href=\"[field:arcurl /]\" target=\"_blank\">【查看更多】</a></span></p>\r\n                        </div>\r\n                    </div>\r\n                    ",676,1341);
$z[3][4]['pagesize']="1";
$z[3][4]['flag']="p";
$z[3][4]['titlelen']="46";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n                            <li>\r\n                                <a href=\"[field:arcurl /] \" target=\"_blank\">\r\n                                    [field:title /]\r\n                                </a>\r\n                            </li>\r\n                            ",1473,1810);
$z[4][4]['row']="6";
$z[4][4]['titlelen']="46";
$z[4][4]['orderby']="pubdate";

?>