<field:zhuanjianame itemname="专家" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhuanjianame>
<field:zuozhentime itemname="坐诊时间" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zuozhentime>


<field:zhicheng itemname="职称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng>
<field:smallpic itemname="小图" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:smallpic>

<field:bigpic itemname="大图" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bigpic>

<field:zhuanjiades itemname="擅长领域" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhuanjiades>


<field:zhuanjiainfor itemname="简历" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zhuanjiainfor>
