<?php
$z[0]=Array("field","",117,146);
$z[0][4]['name']="typename";
$z[1]=Array("field","",236,264);
$z[1][4]['name']="typeurl";
$z[2]=Array("channel","\r\n                <li>\r\n                    <a href=\"[field:typelink/]\" target=\"_blank\">\r\n                        [field:typename/]\r\n                    </a>\r\n                </li>\r\n                ",434,685);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>