<li class="clearfix">
                    <div class="fl">
                        <img src="[field:smallpic/]" style="border: none" alt="[field:title /]">
                    </div>
                    <div class="fr">
                        <h3>[field:zhuanjianame/]</h3>
                        <p>◊¯’Ô ±º‰ :</p>
                        <p>[field:zuozhentime/]</p>
                        <p>
                            [field:zhuanjiamiaoshu function="cn_substr(@me,120)"/]......
                            <span>
                            <a href="[field:arcurl /]" target="_blank">[œÍ«È]</a>
                        </span>
                        </p>
                    </div>
                </li>