<?php
$z[0]=Array("likeart","\r\n        <li class=\"clearfix\">\r\n            <a title=\"[field:title function='htmlspecialchars(@me)'/] \" href=\"[field:arcurl /]\" target=\"_blank\">\r\n                [field:title /]\r\n            </a>\r\n            <span class=\"fr\">{dede:field.click/}</span>\r\n        </li>\r\n        ",122,456);
$z[0][4]['titlelen']="¡¯24¡ä";
$z[0][4]['row']="¡¯10¡ä";

?>