<?php
$z[0]=Array("type","\r\n                    <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                        [field:typename/]\r\n                    </a>\r\n                    ",746,936);
$z[0][4]['typeid']="5";
$z[1]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",1183,1390);
$z[1][4]['typeid']="10";
$z[2]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",1393,1600);
$z[2][4]['typeid']="25";
$z[3]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",1694,1901);
$z[3][4]['typeid']="26";
$z[4]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",1904,2111);
$z[4][4]['typeid']="27";
$z[5]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            ÄÚ·ÖÃÚ¿Æ\r\n                        </a>\r\n                        ",2205,2403);
$z[5][4]['typeid']="28";
$z[6]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",2406,2613);
$z[6][4]['typeid']="29";
$z[7]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",2707,2913);
$z[7][4]['typeid']="9";
$z[8]=Array("type","\r\n                        <a href=\"[field:typeurl/]\" target=\"_blank\">\r\n                            [field:typename/]\r\n                        </a>\r\n                        ",2916,3123);
$z[8][4]['typeid']="10";

?>