<?php
$z[0]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\" class=\"current\">[field:typename /] /</a>\r\n            ",60,209);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",252,385);
$z[1][4]['typeid']="4";
$z[2]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",428,561);
$z[2][4]['typeid']="2";
$z[3]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",604,737);
$z[3][4]['typeid']="3";
$z[4]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",950,1083);
$z[4][4]['typeid']="5";

?>