<?php
$z[0]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\" class=\"current\">[field:typename /] /</a>\r\n            ",63,212);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",255,388);
$z[1][4]['typeid']="4";
$z[2]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",431,564);
$z[2][4]['typeid']="2";
$z[3]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",607,740);
$z[3][4]['typeid']="3";
$z[4]=Array("type","\r\n            <a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /] /</a>\r\n            ",953,1086);
$z[4][4]['typeid']="5";

?>